
version: 2.1

orbs:
  golang: cci-orb/golang@0.1.1
  docker: circleci/docker@0.5.3



jobs:
  test_and_build:
    docker: 
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/harbinger55/rabbit
    steps:
        - checkout
        - run: go test
        - run: go build

  docker_build_and_push:
    executor: docker/machine
    steps:
      - checkout
      - run: go build
      - docker/check
      - docker/build:
          image: harbinger56/rabbit


workflows:
  version: 2
  build_and_test:
    jobs:
      - test_and_build
      - docker_build_and_push

