
version: 2.1

orbs:
  golang: cci-orb/golang@0.1.1
  docker: circleci/docker@0.5.3



jobs:
  build:
    docker: 
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/harbinger55/rabbit
    steps:
        - checkout
        - run: go test
        - run: go build
        - run: docker build -t harbinger56/rabbit:0.0.3 .
        - run: docker push harbinger56/rabbit



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
