
version: 2.1

orbs:
  golang: cci-orb/golang@0.1.1

workflows:
  "rabbit":
    jobs:
    #   docker:
    #     - image: circleci/golang:1.12
    #   working_directory: /go/src/github.com/harbinger55/rabbit
      
      # steps:
      - checkout
      - run: go build

# version: 2.1
# orbs:
#     hello: circleci/hello-build@0.0.5
# workflows:
#     "Hello Workflow":
#         jobs:
#           - hello/hello-build
